<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Produk;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produk = [
            [
                'id_produk' => 'PRD001',
                'nama_produk' => 'Nike Air Max 270',
                'harga' => 1899000,
                'stok' => 15,
                'gambar' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu olahraga premium dengan teknologi Air Max untuk kenyamanan maksimal',
                'merek' => 'Nike',
                'ukuran' => '40-44',
                'warna' => 'Hitam/Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD002',
                'nama_produk' => 'Adidas Ultraboost 22',
                'harga' => 2299000,
                'stok' => 12,
                'gambar' => 'https://images.unsplash.com/photo-1608667508764-33cf0726b13a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu lari dengan teknologi Boost untuk performa terbaik',
                'merek' => 'Adidas',
                'ukuran' => '39-45',
                'warna' => 'Putih/Biru',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD003',
                'nama_produk' => 'Converse Chuck Taylor All Star',
                'harga' => 899000,
                'stok' => 20,
                'gambar' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu kasual klasik dengan desain timeless yang cocok untuk berbagai outfit',
                'merek' => 'Converse',
                'ukuran' => '36-44',
                'warna' => 'Merah',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD004',
                'nama_produk' => 'Vans Old Skool',
                'harga' => 1099000,
                'stok' => 18,
                'gambar' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu skate klasik dengan garis samping khas Vans',
                'merek' => 'Vans',
                'ukuran' => '38-45',
                'warna' => 'Hitam/Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD005',
                'nama_produk' => 'New Balance 997H',
                'harga' => 1599000,
                'stok' => 10,
                'gambar' => 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu retro running dengan bantalan REVlite untuk kenyamanan sepanjang hari',
                'merek' => 'New Balance',
                'ukuran' => '40-46',
                'warna' => 'Abu-abu/Merah',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD006',
                'nama_produk' => 'Puma RS-X³',
                'harga' => 1799000,
                'stok' => 8,
                'gambar' => 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu futuristik dengan desain chunky yang trendy',
                'merek' => 'Puma',
                'ukuran' => '39-44',
                'warna' => 'Putih/Biru/Merah',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD007',
                'nama_produk' => 'Dr. Martens 1460',
                'harga' => 2899000,
                'stok' => 6,
                'gambar' => 'https://images.unsplash.com/photo-1518002171953-a080ee817e1f?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu boots klasik dengan kulit premium dan sol AirWair',
                'merek' => 'Dr. Martens',
                'ukuran' => '37-45',
                'warna' => 'Hitam',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD008',
                'nama_produk' => 'Reebok Classic Leather',
                'harga' => 1199000,
                'stok' => 14,
                'gambar' => 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu kasual retro dengan upper kulit premium',
                'merek' => 'Reebok',
                'ukuran' => '38-44',
                'warna' => 'Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD009',
                'nama_produk' => 'ASICS Gel-Lyte III',
                'harga' => 1399000,
                'stok' => 11,
                'gambar' => 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu running retro dengan teknologi Gel untuk kenyamanan maksimal',
                'merek' => 'ASICS',
                'ukuran' => '39-45',
                'warna' => 'Biru/Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD010',
                'nama_produk' => 'Jordan 1 Retro High',
                'harga' => 2699000,
                'stok' => 5,
                'gambar' => 'https://images.unsplash.com/photo-1556906781-9a412961c28c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu basket ikonik dengan desain klasik yang timeless',
                'merek' => 'Jordan',
                'ukuran' => '40-46',
                'warna' => 'Hitam/Merah/Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD011',
                'nama_produk' => 'Fila Disruptor II',
                'harga' => 1299000,
                'stok' => 16,
                'gambar' => 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu chunky retro dengan sol tebal yang trendy dan nyaman',
                'merek' => 'Fila',
                'ukuran' => '36-42',
                'warna' => 'Putih/Navy/Merah',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD012',
                'nama_produk' => 'Timberland 6-Inch Premium Boot',
                'harga' => 3299000,
                'stok' => 7,
                'gambar' => 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu boot premium dengan kulit nubuck tahan air dan konstruksi yang kuat',
                'merek' => 'Timberland',
                'ukuran' => '39-46',
                'warna' => 'Wheat/Cokelat',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD013',
                'nama_produk' => 'Skechers D\'Lites',
                'harga' => 1199000,
                'stok' => 22,
                'gambar' => 'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu kasual dengan memory foam untuk kenyamanan sepanjang hari',
                'merek' => 'Skechers',
                'ukuran' => '36-44',
                'warna' => 'Putih/Silver',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD014',
                'nama_produk' => 'Under Armour HOVR Phantom 3',
                'harga' => 2199000,
                'stok' => 9,
                'gambar' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu running dengan teknologi HOVR untuk cushioning yang responsif',
                'merek' => 'Under Armour',
                'ukuran' => '40-45',
                'warna' => 'Hitam/Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD015',
                'nama_produk' => 'Onitsuka Tiger Mexico 66',
                'harga' => 1599000,
                'stok' => 13,
                'gambar' => 'https://images.unsplash.com/photo-1539185441755-769473a23570?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu heritage dengan desain vintage dan kualitas premium Jepang',
                'merek' => 'Onitsuka Tiger',
                'ukuran' => '38-44',
                'warna' => 'Kuning/Hitam',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD016',
                'nama_produk' => 'Keds Champion Originals',
                'harga' => 799000,
                'stok' => 25,
                'gambar' => 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu kanvas klasik yang simpel dan versatile untuk gaya kasual',
                'merek' => 'Keds',
                'ukuran' => '36-42',
                'warna' => 'Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD017',
                'nama_produk' => 'Mizuno Wave Rider 26',
                'harga' => 2099000,
                'stok' => 8,
                'gambar' => 'https://images.unsplash.com/photo-1552346154-21d32810aba3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu running dengan teknologi Wave untuk stabilitas dan smooth ride',
                'merek' => 'Mizuno',
                'ukuran' => '39-45',
                'warna' => 'Biru/Putih',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD018',
                'nama_produk' => 'Clarks Desert Boot',
                'harga' => 1899000,
                'stok' => 12,
                'gambar' => 'https://images.unsplash.com/photo-1478720568477-b2709de7c9c6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu boot suede klasik dengan sole crepe untuk gaya kasual elegan',
                'merek' => 'Clarks',
                'ukuran' => '39-45',
                'warna' => 'Beeswax/Cokelat',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD019',
                'nama_produk' => 'Diadora N9000',
                'harga' => 1399000,
                'stok' => 14,
                'gambar' => 'https://images.unsplash.com/photo-1595341888016-a392ef81b2de?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu running retro Italia dengan desain yang elegan dan berkualitas',
                'merek' => 'Diadora',
                'ukuran' => '40-44',
                'warna' => 'Abu-abu/Biru',
                'dibuat_pada' => now(),
            ],
            [
                'id_produk' => 'PRD020',
                'nama_produk' => 'Hoka One One Clifton 9',
                'harga' => 2399000,
                'stok' => 6,
                'gambar' => 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80',
                'deskripsi' => 'Sepatu running ultra-cushioned untuk kenyamanan maksimal dalam berlari jarak jauh',
                'merek' => 'Hoka One One',
                'ukuran' => '40-46',
                'warna' => 'Putih/Biru',
                'dibuat_pada' => now(),
            ],
        ];

        foreach ($produk as $item) {
            Produk::create($item);
        }
    }
}
